# Generated by Django 4.2.1 on 2023-06-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='Person_name',
        ),
    ]
